version: '3.8'

services:
  server:
    container_name: server
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: '.env'
    networks:
      - appnet
    depends_on:
      - database
      - cache
    ports:
      - '3000:3000'
    command: yarn run start:dev

  database:
    container_name: database
    image: postgres:15
    restart: always
    networks:
      - appnet
    ports:
      - '5432:5432'
    volumes:
      - db_val:/var/lib/postgresql/data
    env_file: '.env'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  cache:
    image: redis:7.2-rc1-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

networks:
  appnet:

volumes:
  db_val:
    driver: local
  app:
    driver: local
  cache:
    driver: local
